Various fixups for package scripts.

diff --git a/package-scripts/api-umbrella/postinst b/package-scripts/api-umbrella/postinst
--- a/package-scripts/api-umbrella/postinst
+++ b/package-scripts/api-umbrella/postinst
@@ -4,36 +4,46 @@
 # after package is installed.
 #
 
-PROGNAME=$(basename $0)
-
-function error_exit
-{
-  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+function error_exit {
+  echo "api-umbrella: ${1:-"Unknown Error"}" 1>&2
   exit 1
 }
 
-adduser --system --quiet --group --no-create-home api-umbrella
-adduser --system --quiet --group --no-create-home api-umbrella-deploy
+USER=api-umbrella
+GROUP=api-umbrella
+DEPLOY_USER=api-umbrella-deploy
+DEPLOY_GROUP=api-umbrella-deploy
 
+getent group $GROUP > /dev/null || groupadd -r $GROUP
+getent passwd $USER > /dev/null || \
+  useradd -r -g $GROUP -s /sbin/nologin \
+    -d /opt/api-umbrella -c "API Umbrella user" $USER
+
+getent group $DEPLOY_GROUP > /dev/null || groupadd -r $DEPLOY_GROUP
+getent passwd $DEPLOY_USER > /dev/null || \
+  useradd -r -g $DEPLOY_GROUP -s /sbin/nologin \
+    -d /opt/api-umbrella/embedded/apps -c "API Umbrella deployment user" $DEPLOY_USER
+
+mkdir -p /opt/api-umbrella/etc
+mkdir -p /opt/api-umbrella/var/db
+mkdir -p /opt/api-umbrella/var/log
+mkdir -p /opt/api-umbrella/var/run
 mkdir -p /opt/api-umbrella/var/tmp
 chmod 1777 /opt/api-umbrella/var/tmp
 
-chown api-umbrella:api-umbrella /opt/api-umbrella/etc /opt/api-umbrella/var
+chown -R api-umbrella:api-umbrella /opt/api-umbrella/etc /opt/api-umbrella/var
 chown -R api-umbrella-deploy:api-umbrella-deploy /opt/api-umbrella/embedded/apps
 
 ln -sf /opt/api-umbrella/bin/api-umbrella /usr/bin/api-umbrella || error_exit "Cannot link api-umbrella to /usr/bin"
-ln -sf /opt/api-umbrella/etc/init.d/api-umbrella /etc/init.d/api-umbrella || error_exit "Cannot link api-umbrella to /etc/init.d"
+cp /opt/api-umbrella/etc/init.d/api-umbrella /etc/init.d/api-umbrella || error_exit "Cannot copy api-umbrella to /etc/init.d"
 
-if [ command -v chkconfig > /dev/null 2>&1 ]; then
+# Install service, but don't activate.
+if command -v chkconfig > /dev/null 2>&1; then
   chkconfig --add api-umbrella || error_exit "Cannot enable api-umbrella service"
-elif [ command -v update-rc.d > /dev/null 2>&1 ]; then
+elif command -v update-rc.d > /dev/null 2>&1; then
   update-rc.d api-umbrella defaults 85 15 || error_exit "Cannot enable api-umbrella service"
 else
   error_exit "No supported init tool found."
 fi
-
-/etc/init.d/api-umbrella start || error_exit "Cannot start api-umbrella service"
-
-echo "Thank you for installing api-umbrella!"
 
 exit 0
diff --git a/package-scripts/api-umbrella/postrm b/package-scripts/api-umbrella/postrm
--- a/package-scripts/api-umbrella/postrm
+++ b/package-scripts/api-umbrella/postrm
@@ -4,21 +4,16 @@
 # after package is uninstalled.
 #
 
-PROGNAME=$(basename $0)
-
-function error_exit
-{
-  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+function error_exit {
+  echo "api-umbrella: ${1:-"Unknown Error"}" 1>&2
   exit 1
 }
 
-cleanup() {
-  if [ command -v chkconfig > /dev/null 2>&1 ]; then
-    chkconfig --del api-umbrella || error_exit "Cannot disable api-umbrella service"
-  elif [ command -v update-rc.d > /dev/null 2>&1 ]; then
-    update-rc.d api-umbrella remove || error_exit "Cannot disable api-umbrella service"
-  else
-    error_exit "No supported init tool found."
+function remove_service {
+  if command -v chkconfig > /dev/null 2>&1; then
+    chkconfig --del api-umbrella > /dev/null 2>&1
+  elif command -v update-rc.d > /dev/null 2>&1; then
+    update-rc.d api-umbrella remove > /dev/null 2>&1
   fi
 
   rm -f /usr/bin/api-umbrella
@@ -32,16 +27,15 @@ cleanup() {
 # See: http://tickets.opscode.com/browse/CHEF-3022
 if [ ! -f /etc/redhat-release -a ! -f /etc/fedora-release -a ! -f /etc/system-release ]; then
   # Non-RPM system: Go ahead with removal
-  cleanup
-elif [ $1 -eq 0 ]; then
+  remove_service
+elif [ "$1" -eq "0" ]; then
   # RPM system: Uninstalling (not upgrading)
-  cleanup
-elif [ $1 -ge 1 ]; then
+  remove_service
+elif [ "$1" -eq "1" ]; then
   # RPM system: Upgrading (not uninstalling)
-  /etc/init.d/api-umbrella status || exit 0
-  /etc/init.d/api-umbrella restart || error_exit "Cannot start api-umbrella service"
+  # Restart, but only if started.
+  /etc/init.d/api-umbrella status > /dev/null 2>&1 || exit 0
+  /etc/init.d/api-umbrella restart > /dev/null 2>&1 || error_exit "Cannot restart api-umbrella service"
 fi
-
-echo "api-umbrella has been uninstalled!"
 
 exit 0
